apiVersion: v1
kind: ConfigMap
metadata:
  name: my-scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceName: my-energy-scheduler-lock
      resourceNamespace: kube-system
    profiles:
      - schedulerName: my-energy-scheduler
        plugins:
          preScore:
            enabled:
              - name: EnergyScorer
          filter:
            enabled:
              - name: NodeUnschedulable
              - name: NodeName
              - name: TaintToleration
              - name: NodeResourcesFit
          score:
            enabled:
              - name: EnergyScorer
                weight: 100
              - name: NodeResourcesBalancedAllocation
                weight: 1
              - name: ImageLocality
                weight: 1
        pluginConfig:
          - name: EnergyScorer
            args: {}
